routes/front.php
<?php
use Illuminate\Support\Facades\Route;

Route::post('/cookie/store', [\App\Http\Controllers\CookiesController::class, 'store'])->name('cookies.store');

Route::group(['prefix'=>'with-component-path', 'middleware'=>['locale.front']], function() {
    Route::get('/{slug?}',  [\App\Http\Controllers\PagesController::class, 'index']);
    Route::get('/{type}/{slug}', [\App\Http\Controllers\PagesController::class, 'show']);
    Route::post('form_submit', [\App\Http\Controllers\FormsController::class, 'store'])->name('form.submit.default');
    Route::get('api/article/get', [\App\Http\Controllers\ArticleController::class, 'get'])->name('api.article.get');

    Route::get('api/category/{id}', [\App\Http\Controllers\CategoryController::class, 'show'])->name('api.category.show');
    Route::get('api/category/get_childrens/{category}', [\App\Http\Controllers\CategoryController::class, 'getChildrens']);
    Route::get('api/category/get_all_childrens/{category}',[\App\Http\Controllers\CategoryController::class, 'getAllChildrens']);
});

foreach(cache('front_available_locales', []) as $locale=>$lang)
{

    Route::group(['prefix'=>$locale, 'middleware'=>['locale.front']], function() {
        Route::get('/{slug?}',  [\App\Http\Controllers\PagesController::class, 'index']);
        Route::get('/{type}/{slug}', [\App\Http\Controllers\PagesController::class, 'show']);
        Route::post('form_submit', [\App\Http\Controllers\FormsController::class, 'store'])->name('form.submit.default');
    });

}


Route::group(['prefix'=>'', 'middleware'=>['locale.front']], function() {
    Route::get('/{slug?}',  [\App\Http\Controllers\PagesController::class, 'index']);
    Route::get('/{type}/{slug}', [\App\Http\Controllers\PagesController::class, 'show']);
    Route::post('form_submit', [\App\Http\Controllers\FormsController::class, 'store'])->name('form.submit.default');
    Route::get('api/article/get', [\App\Http\Controllers\ArticleController::class, 'get'])->name('api.article.get');

    Route::get('api/category/{id}', [\App\Http\Controllers\CategoryController::class, 'show'])->name('api.category.show');
    Route::get('api/category/get_childrens/{category}', [\App\Http\Controllers\CategoryController::class, 'getChildrens']);
    Route::get('api/category/get_all_childrens/{category}',[\App\Http\Controllers\CategoryController::class, 'getAllChildrens']);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Spatie\Sitemap\SitemapGenerator;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Route::get('/linkstorage', function () {
//    $exitCode = Artisan::call('storage:link', [] );
//    echo $exitCode; // 0 exit code for no errors.
//});


Route::get('sitemap.xml', function(){
    //return SitemapGenerator::create('http://localhost')->getSitemap();
});

Route::group(['middleware'=>['locale.front']], function() {
    Auth::routes();
});

Route::get('register', function(){
    abort(404, 'Not allowed');
});
Route::post('register', function(){
    abort(404, 'Not allowed');
});

require('api.php');
//require('cms.php');
require('tests.php');
require('front.php');



//Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Component.php
<?php

namespace App\Models;

use App\Interfaces\Fieldable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Packages\Orders\App\Models\Checkout;
use Packages\PaymentsMethods\App\Models\PaymentMethod;
use Packages\Store\app\Models\Product;

class Component extends Model implements Fieldable
{
    use HasFactory;

    protected $guarded = ['id', 'created_at', 'updated_at'];
    protected $casts = ['is_template'=>'boolean'];

    public function fields()
    {
        return $this->morphMany(Field::class, 'fieldable')->ordered();
    }

    public function terms()
    {
        return $this->morphMany(Term::class, 'termable');
    }

    public function possibleComponentableTypes()
    {
        $possible_types = [
            null => __('cms.global'),
            Article::class => __('cms.article')
        ];

        if(env('APP_STORE'))
        {
            $possible_types = array_merge($possible_types, [
                Product::class=>__('store::cms.product'),
            ]);
        }
        if(env('APP_ORDERS'))
        {
            $possible_types = array_merge($possible_types, [
                Checkout::class=>__('order::cms.checkout'),
            ]);
        }
        if(env('APP_PAYMENT_METHODS'))
        {
            $possible_types = array_merge($possible_types, [
                PaymentMethod::class=>__('payment_methods::cms.payment_methods'),
            ]);
        }

        return $possible_types;
    }

    public function getTerms()
    {
        $data = new \stdClass();
        foreach($this->terms as $term)
        {
            $key=$term->key;
            $data->$key = $term->value;
        }
        return $data;
    }

    public function avaliableFields()
    {
        $field_types = [
            'text' => 'Campo de texto',
            'textarea-single'=>'Textarea sem editor',
            'textearea-editor'=>'Textarea com editor',
            'integer'=>'Campo para números inteiros',
            'date'=>'Campo de data',
            'select-single'=>'Select uma opção',
            'select-multiple'=>'Select multiplas opções',
            'checkbox'=>'Checkox',
            'option'=>'Option',
            'image'=>'Imagens',
            'doc'=>'Documentos',
            'video'=>'Videos',
            'internal_link'=>'Link interno',
            'menu'=>'Menu',
            'form'=>'Formulário',
            'texts-list'=>'Lista de textos',
            'articles-list'=>'Lista de artigos',
            'titles-texts-list'=>'Lista de textos com titulos',
            'category-list'=>'Lista de categorias',
            'tags-list'=>'Lista de tags'
        ];

        if(env('APP_STORE'))
        {
            $field_types = array_merge($field_types, [
                'products-list'=>'Lista de produtos',
                'attributes-list'=>'Lista de atributos'
            ]);
        }

        if(env('APP_DOCUMENTS'))
        {
            $field_types = array_merge($field_types, [
                'documents-list'=>'Lista de documentos (modelo)'
            ]);
        }

        if(env('APP_IMAGE_HOTSPOTS'))
        {
            $field_types = array_merge($field_types, [
                'image-hotspots'=>'Imagem com Hotspots'
            ]);
        }

        return $field_types;
    }

    public function hasFieldGroups()
    {
        return false;
    }
}

app/Models/Form.php
<?php

namespace App\Models;

use App\Interfaces\Fieldable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Form extends Model implements Fieldable
{
    use HasFactory;

    protected $guarded = [];

    protected $casts = [
        'can_see_answears'=>'boolean',
        'can_add_fields'=>'boolean',
        'apply_recaptcha'=>'boolean'
    ];

    public function fields()
    {
        return $this->morphMany(Field::class, 'fieldable');
    }

    public function fieldGroups()
    {
        return $this->morphMany(FieldGroup::class, 'field_groupable');
    }

    public function getFieldGroupsWithFields()
    {
        return $this->fieldGroups()->with(['fields' => function($q){
            $q->ordered();
        }])->ordered()->get();
    }

    public function submissions()
    {
        return $this->hasMany(FormSubmission::class);
    }

    public function getEndPointAttribute()
    {
        if ( ! empty($this->formable))
        {
            return $this->formable->getEndPointForm($this->type);
        }
        return route('form.submit.default');
    }

    public function formable()
    {
        return $this->morphTo();
    }

    public function getCmsFormIdAttribute()
    {
        return $this->id;
    }

    public function avaliableFields()
    {
        return [
            'text'=>'cms.field_text',
            'textarea-single'=>'cms.textarea-single',
            'integer'=>'cms.integer',
            'date'=>'cms.date',
            'checkbox'=>'cms.checkbox',
            'select-single'=>'cms.select-single',
            'select-multiple'=>'cms.select-multiple',
            'doc'=>'cms.doc'
        ];
    }

    //TODO::A Eliminar no futuro
    public function setEmailReceiversAttribute($value)
    {
        $this->attributes['email_receivers'] = json_encode($value);
    }
    //TODO::A Eliminar no futuro
    public function getEmailReceiversAttribute($value)
    {
        return json_decode($value, true);
    }

    public function hasFieldGroups()
    {
        return $this->fieldGroups()->exists();
    }
}

resources/views/front/components/footer/footer.blade.php
<footer class="secondary-bg px-app">
    <div class="container-fluid py-5">
        <div class="row pb-5">
            <div class="col-lg-6 border-end mb-5 mb-lg-2">
                <div class="d-flex justify-content-lg-center">
                    <div class="text-white">
                        <h4 class="h4 yellow-text mb-4">{{$data->title_top_left->default}}</h4>
                        <h5 class="mb-4">
                            {{$data->description_top_left->default}}
                        </h5>
                        <div class="d-flex">
                            @foreach($data->social_network->default as $item)
                            <a class="me-2" href="{{$item['text']}}">
                                <div>
                                    @include('front.components.footer.social_icons', ['icon'=>$item['title']])
                                </div>
                            </a>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="d-flex justify-content-lg-center">
                    <div class="text-white">
                        <h4 class="h4 yellow-text mb-4">{{$data->title_top_right->default}}</h4>
                        <h5 class="mb-4">
                            {{$data->description_top_right->default}}
                        </h5>
                        <div class="d-flex">
                            <form class="input-group mb-3 rounded-2 overflow-hidden" style="border-color: #ffb100" method="post" action="{{$data->newsletter->default->end_point}}">
                                <div>
                                    @csrf
                                    <input type="hidden" name="cms_form_id" value="{{$data->newsletter->default->id}}">
                                    @foreach($data->newsletter->default->fields as $field)
                                    <label for="email-address" class="sr-only">hlw{{$field->label}}</label>
                                    <input type="text" name="{{$field->name}}" id="email-address" autocomplete="email" required class="form-control secondary-bg" style="border-color: #ffb100" placeholder="Enter your email">
                                    @endforeach
                                </div>
                                <!-- <input type="text" class="form-control bg-transparent" placeholder="E-mail" aria-label="Recipient's username" aria-describedby="basic-addon2" style="border-color: #ffb100" /> -->
                                <button class="input-group-text bg-transparent text-white" id="basic-addon2" type='submit' style="border-color: #ffb100">{{$data->submit->default}}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top p-0 pt-5 p-lg-5">
            <div class="col"></div>
            <div class="col-lg-2 footer-links">
                <a class="heading">
                    <h4 class="mb-5">{{$data->title_first_menu->default}}</h4>
                </a>
                @foreach($data->menu_1->default->items as $item)
                <a href="{{$item->path}}">
                    <p class="ms-3 mb-3">{{$item->name}}</p>
                </a>
                @endforeach
            </div>
            <div class="col-lg-2 footer-links">
                <a class="heading">
                    <h4 class="mb-5">{{$data->title_second_menu->default}}</h4>
                </a>
                @foreach($data->menu_2->default->items as $item)
                <a href="{{$item->path}}">
                    <p class="ms-3 mb-3">{{$item->name}}</p>
                </a>
                @endforeach
            </div>
            <div class="col-lg-2 pt-7 footer-links">

                @foreach($data->central_menu->default->items as $item)
                <a class='heading' href="{{$item->path}}">
                    <p class="ms-3 mb-3">{{$item->name}}</p>
                </a>
                @endforeach
            </div>
            
            <div class="col-lg-2 footer-links">
                <a class="heading">
                    <h4 class="mb-5">{{$data->title_four_menu->default}}</h4>
                </a>
                @foreach($data->menu_4->default->items as $item)
                <a href="{{$item->path}}">
                    <p class="ms-3 mb-3">{{$item->name}}</p>
                </a>
                @endforeach
            </div>
            
            <div class="col-lg-2 footer-links">
                <a class="heading">
                    <h4 class="mb-5">{{$data->title_five_bar->default}}</h4>
                </a>
                <div class="ms-3 mb-3 text-white">
                        {!! $data->contact->default !!}
                </div>
                @foreach($data->menu_5->default->items as $item)
                <a href="{{$item->path}}">
                    <p class="ms-3 mb-3">{{$item->name}}</p>
                </a>
                @endforeach
            </div>
            <div class="col"></div>
        </div>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

resources/views/front/components/footer/social_icons.blade.php
@if(strtolower($icon) === 'facebook')
    <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <path fill-rule="evenodd"
              d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
              clip-rule="evenodd"/>
    </svg>
@endif
@if(strtolower($icon) === 'instagram')
    <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd" />
    </svg>
@endif
@if(strtolower($icon) === 'twitter')
    <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <path
            d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"/>
    </svg>
@endif